version: '3.7'
services: 
  cloud2020-88690:
    image: mysql:5
    environment:
        MYSQL_ROOT_USER: sgrajper
        MYSQL_ROOT_PASSWORD: slawek
        MYSQL_DATABASE: users
        MYSQL_USER: sgrajper
        MYSQL_PASSWORD: slawek
    volumes: 
        - ./mysql/insert.sql:/docker-entrypoint-initdb.d/insert.sql
    networks:
      Bridge-zadanie-1:
        ipv4_address: 10.1.10.4
    ports: 
      - "3307:3307"

  javaapp:
    build:
        context: ./java
    restart: on-failure
    depends_on:
        - cloud2020-88690
    container_name: javaapp
    networks:
      - Bridge-zadanie-1
    stdin_open: true
    tty: true
networks: 
  Bridge-zadanie-1:
    driver: bridge
    ipam: 
      config: 
        - subnet: 10.1.10.0/24   
